on:
  push:
    branches:
      - ekw/SRE-1005/release-static-libraries

env:
  SERVICE_NAME: "static-libraries"
  RUST_VERSION: "1.73.0"
  GHC_VERSION: "9.6.4"
  PROTOC_VERSION: "3.15.3"
  FLATBUFFERS_VERSION: "v22.12.06"
  NVM_SH_VERSION: "v0.37.2"
  CMAKE_VERSION: "3.25.1"

jobs:
  release-base-image:
#    if: ${{ startsWith(github.ref_name, '${{env.SERVICE_NAME}}') }}
    uses: concordium/.github/.github/workflows/docker-release-workflow.yaml@ekw/workflow-templates
    with:
      SERVICE_NAME: "static-libraries"
      BUILD_ARGS: |
        rust_version=1.73.0
        ghc_version=9.6.4
        protoc_version=3.15.3
        flatbuffers_tag=v22.12.06
        nvm_sh_version=v0.37.2
        cmake_version=3.25.1
      DOCKER_FILE: docker/base.Dockerfile
    secrets: inherit