on:
  push:
    tags:
      - static-libraries/*

jobs:
  release-static-libraries-image:
    uses: concordium/.github/.github/workflows/docker-release-workflow.yaml@v1
    with:
      SERVICE_NAME: "static-libraries"
      BUILD_ARGS: |
        UBUNTU_VERSION=20.04
        RUST_VERSION=1.82
        GHC_VERSION=9.10.2
        STACK_VERSION=3.1.1
        PROTOC_VERSION=28.3
      DOCKER_FILE_PATH: docker/static-libraries.Dockerfile
    secrets: inherit
