on:
  push:
    branches:
      - ekw/SRE-1005/release-static-libraries

env:
  SERVICE_NAME: "static-libraries"
  RUST_VERSION: "1.73.0"
  GHC_VERSION: "9.6.4"
  PROTOC_VERSION: "3.15.3"
  FLATBUFFERS_VERSION: "v22.12.06"
  NVM_SH_VERSION: "v0.37.2"
  CMAKE_VERSION: "3.25.1"
  BUILD_ARGS: |
    rust_version=${{ env.RUST_VERSION }}
    ghc_version=${{ env.GHC_VERSION }}
    protoc_version=${{ env.PROTOC_VERSION }}
    flatbuffers_tag=${{ env.FLATBUFFERS_VERSION }}
    nvm_sh_version=${{ env._NVM_SH_VERSION }}
    cmake_version=${{ env.CMAKE_VERSION }}

jobs:
  release-base-image:
#    if: ${{ startsWith(github.ref_name, '${{env.SERVICE_NAME}}') }}
    uses: concordium/.github/.github/workflows/docker-release-workflow.yaml@ekw/workflow-templates
    with:
      SERVICE_NAME: "static-libraries"
      BUILD_ARGS: ${{ env.BUILD_ARGS }}
      DOCKER_FILE: docker/base.Dockerfile
    secrets: inherit