on:
  push:
    tags:
      - static-libraries/*

jobs:
  release-static-libraries-image:
    uses: concordium/.github/.github/workflows/docker-release-workflow.yaml@main
    with:
      SERVICE_NAME: "static-libraries"
      BUILD_ARGS: |
        ubuntu_version=20.04
        rust_version=1.73.0
        ghc_version=9.6.4
        stack_version=2.13.1
        protoc_version=3.15.3
      DOCKER_FILE: docker/static-libraries.Dockerfile
      VERSION: "rust-1.73.0_ghc-9.6.4"
    secrets: inherit
