on:
  push:
    branches:
      - ekw/SRE-1005/release-static-libraries
#    tags:
#      - static-libraries-*



jobs:
  release-base-image:
#    if: ${{ startsWith(github.ref_name, '${{env.SERVICE_NAME}}') }}
    uses: concordium/.github/.github/workflows/docker-release-workflow.yaml@ekw/workflow-templates
    with:
      SERVICE_NAME: "static-libraries"
      BUILD_ARGS: |
        ubuntu_version=20.04
        rust_version=1.73.0
        ghc_version=9.6.4
        stack_version=2.13.1
        protoc_version=3.15.3
      DOCKER_FILE: docker/static-libraries.Dockerfile
      VERSION: "1.2.4"
    secrets: inherit
