on:
  push:
    tags:
      - fpic-ghc/*

env:
  AWS_ROLE_TO_ASSUME: "arn:aws:iam::192549843005:role/github_concordium-ghc"
  GHC_VERSION: "9.6.6"
  BOOTSTRAP_GHC_VERSION: "9.6.4"

permissions:
  id-token: write
  contents: read

jobs:
  release-fpic:
    runs-on: ubuntu-latest
    environment: release
    steps:
      
      - name: aws creds
        uses: aws-actions/configure-aws-credentials@v4
        id: creds
        with:
          aws-region: "eu-west-1"
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-session-name: ReleaseAlpineGhcSession
      
      - name: Build and push
        run: |
          # GHC_VERSION corresponds to the version of GHC that we are building.
          # BOOTSTRAP_GHC_VERSION corresponds to the version of GHC that we are using to build GHC_VERSION.
          GHC_VERSION="${{ env.GHC_VERSION }}" \
          BOOTSTRAP_GHC_VERSION="${{ env.BOOTSTRAP_GHC_VERSION }}" \
          ./scripts/ghc-alpine-build.sh
