on: 
  push:
    tags:
      - release/base-image-*
  
jobs:
  release-base-image:
    if: ${{ startsWith(github.ref_name, 'release/base-image') }}
    runs-on: ubuntu-latest
    environment: release
    env:
      SERVICE_NAME: "concordium/base"
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
      RUST_VERSION: "1.73.0"
      GHC_VERSION: "9.6.4"
      PROTOC_VERSION: "3.15.3"
      FLATBUFFERS_VERSION: "v22.12.06"
      NVM_SH_VERSION: "v0.37.2"
      CMAKE_VERSION: "3.25.1"

    steps:
      - name: Get the Image tag
        env:
          TAG: ${{ github.ref_name }}
        run: echo "IMAGE_TAG=${TAG##release/base-image-}" >> $GITHUB_ENV

      - name: Check if image exist
        run: |
          set +e
          docker manifest inspect ${{env.SERVICE_NAME}}:${{env.IMAGE_TAG}}
          exitcode=$?
          if [ $exitcode -eq "0" ]; then
            echo "Error: ${{env.SERVICE_NAME}}:rust${{env.RUST_VERSION}}-ghc${{env.GHC_VERSION}} already exist"
            exit 1
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Clone repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/base.Dockerfile
          tags: ${{ env.IMAGE_TAG }}
          no-cache: true
          push: false
          ssh: |
            default=./id_rsa
          build-args: |
            rust_version="${{env.RUST_VERSION}}"
            ghc_version="${{env.GHC_VERSION}}"
            protoc_version="${{env.PROTOC_VERSION}}"
            flatbuffers_tag="${{env.FLATBUFFERS_VERSION}}"
            nvm_sh_version="${{env.NVM_SH_VERSION}}"
            cmake_version="${{env.CMAKE_VERSION}}"

      #- name: build docker image
      #  run: |
      #    docker build --build-arg rust_version="${{env.RUST_VERSION}}" --build-arg ghc_version="${{env.GHC_VERSION}}" --build-arg protoc_version="${{env.PROTOC_VERSION}}" --build-arg flatbuffers_tag="${{env.FLATBUFFERS_VERSION}}" --build-arg nvm_sh_version="${{env.NVM_SH_VERSION}}" --build-arg cmake_version="${{env.CMAKE_VERSION}}" --label rust_version="${{env.RUST_VERSION}}" --label ghc_version="${{env.GHC_VERSION}}" -f "docker/base.Dockerfile" -t "${{env.SERVICE_NAME}}:${{env.IMAGE_TAG}}" .
#
      #- name: Push docker image
      #  run: |
      #    docker push ${{env.SERVICE_NAME}}:${{env.IMAGE_TAG}}
